
STATE_KEY="IL"
COUNTY_KEY="MHC1"
PREFIX_EV="EV"
PREFIX_FC="FC"
PREFIX_LA="LA"
PREFIX_LM="LM"
PREFIX_PR="PR"
PREFIX_OP="OP"
PREFIX_CH="CH"
PREFIX_WI="WI"
PREFIX_MR="MR"
PREFIX_AR="AR"
PREFIX_DN="DN"
PREFIX_SC="SC"
PREFIX_DC="DC"
PREFIX_DV="DV"
PREFIX_LF="LF"
PREFIX_FA="FA"
# IL_MHC1 configurations
python /usr/local/lib/python3.9/site-packages/core/patch/ongoing/update_county_info/update_county_info.py --state_key $STATE_KEY --county_key $COUNTY_KEY --extractor_directory_path /root/legal-beagles/src/il/mchenry_county --extractor_file extractor_il_mhc1.py --db_host $CODAXTR_DBHOST --update_database --time_zone 'US/Central'

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# IL_MHC1 Regular Extractors
# 1. Incremental Next Gen Extractor
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_EV --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_FC --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_LA --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_LM --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_PR --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_OP --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_CH --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_WI --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_MR --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_AR --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_DN --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_SC --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_DC --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_DV --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_LF --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_next_gen_config.py  --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host $CODAXTR_DBHOST --prefix $PREFIX_FA --start_case_number 1 --number_of_cases_to_fetch 100 --threshold 25 --number_of_digits_in_seed 6 --case_number_pattern {year}{prefix}{seed_number} --update_database --year 2024


# --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# IL_MHC1 Ramp-Up Extractors
# 1. Incremental Extractor
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_EV --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_FC --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_LA --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_LM --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database 
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_PR --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_OP --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_CH --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_WI --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_MR --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_AR --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_DN --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_SC --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_DC --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_DV --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_LF --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database
python3 /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/create_incremental_extractor.py --state_key $STATE_KEY --county_key $COUNTY_KEY --db_host  $CODAXTR_DBHOST --prefix $PREFIX_FA --is_ramp_up --start_case_number 1 --stop_case_number 9999 --number_of_cases_to_fetch 200 --threshold 20 --number_of_digits_in_case_number 6 --ramp_up_gap_between_runs_in_min 30 --update_database

# --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#IL_MHC1 Required Extractors
python /usr/local/lib/python3.9/site-packages/core/patch/ongoing/court_onboarding/required_extractors_for_setup.py --state_key $STATE_KEY --county_key $COUNTY_KEY --update_database --db_host $CODAXTR_DBHOST
